config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users
  resources :users
  resources :taps
  get 'simple_pages/index'
  
  root 'simple_pages#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :manage, User, id: user.id
    can :manage, Tap, id: user.id
    can :manage, Event, id: user.id
    can :read, :all
    can :manage, :all
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/tap.rb
class Tap < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    authorize! :show, @project
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :scheduled_time, :image_url, :description)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
    @events = Event.all
    @taps = Tap.all
  end
end

app/controllers/taps_controller.rb
class TapsController < ApplicationController
  before_action :set_tap, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /taps
  # GET /taps.json
  def index
    @taps = Tap.all
  end

  # GET /taps/1
  # GET /taps/1.json
  def show
    authorize! :show, @project
  end

  # GET /taps/new
  def new
    @tap = Tap.new
  end

  # GET /taps/1/edit
  def edit
  end

  # POST /taps
  # POST /taps.json
  def create
    @tap = Tap.new(tap_params)

    respond_to do |format|
      if @tap.save
        format.html { redirect_to @tap, notice: 'Tap was successfully created.' }
        format.json { render :show, status: :created, location: @tap }
      else
        format.html { render :new }
        format.json { render json: @tap.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taps/1
  # PATCH/PUT /taps/1.json
  def update
    respond_to do |format|
      if @tap.update(tap_params)
        format.html { redirect_to @tap, notice: 'Tap was successfully updated.' }
        format.json { render :show, status: :ok, location: @tap }
      else
        format.html { render :edit }
        format.json { render json: @tap.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taps/1
  # DELETE /taps/1.json
  def destroy
    @tap.destroy
    respond_to do |format|
      format.html { redirect_to taps_url, notice: 'Tap was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tap
      @tap = Tap.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tap_params
      params.require(:tap).permit(:name, :brewery, :style, :color, :description, :img_url, :draft, :abv, :now_on)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/helpers/taps_helper.rb
module TapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :scheduled_time %>
    <%= f.datetime_select :scheduled_time %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="titlelogo">Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="titlelogo">Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Scheduled time</th>
      <th>Image url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.order(:scheduled_time).each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.scheduled_time %></td>
        <td><%= event.image_url %></td>
        <td><%= event.description %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1 class="titlelogo">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Scheduled time:</strong>
  <%= @event.scheduled_time %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @event.image_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Holy GrALE</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <script src="path/to/parallax.js"></script>

  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Bellefair|Cinzel', media: 'all', 'data-turbolinks-track' => true %>
</head>
<body>

<%= yield %>

<footer>
    <p>&copy; 2018 The Holy GrALE |
      <% if user_signed_in? %>
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %> | 
        <%= link_to "Home", simple_pages_index_path %> |
        <%= link_to "Taps", taps_path %> |
        <%= link_to "Users", users_path %> |
        <%= link_to "Events", events_path %>
      <% else %>
        <%= link_to('Login', new_user_session_path) %>
      <% end %>
    </p>

</footer>
</body>
</html>

app/views/simple_pages/index.html.erb
<div class="container-fluid">
  <div id="home" class="row">
    <div class="parallax"></div>
  </div>
  <div class="row">
    <div class="labelbox">
      <h1 class="titlelogo">the holy grALE</h1>
      <p class="texts">Castle Park | Lancaster</p>
      <p class="texts">Real Ale | Less-Than-Awful Food | Grumpy Barstaff</p>
    </div>
    <div id='navy'>
      <ul class='navy_items'>
        <li><a href="#home">Home</a></li>
        <li> | </li>
        <li><a href="#about">About Us</a></li>
        <li> | </li>
        <li><a href="#hours">Hours</a></li>
        <li> | </li>
        <li><a href="#whatson">What's On?</a></li>
        <li> | </li>
        <li><a href="#events">Events</a></li>
        <li> | </li>
        <li><a href="#contact">Contact Us</a></li>
      </ul>
    </div>
  </div>
  <div id="about" class="row">
    <div class="parallax"></div>
  </div>
  <div class="row">
    <div class="infobox">
      <h2 class="mintitle">About Us</h2>
      <p class="texty">Located in downtown Lancaster. The ideal place to find great real ales and artisinal food.</p>
    </div>
  </div>
  <div id="hours"  class="row">
    <div class="parallax2"></div>
  </div>
  <div class="row">
    <div class="infobox">
      <h2 class="mintitle">Hours</h2>
        <div class="beer texty">Monday, Tuesday, Wednesday, Thursday | 2pm - 10pm</div>
        <div class="beer texty">Friday, Saturday | Noon - Midnight</div>
        <div class="beer texty">Sunday | Noon - 10pm</div>
    </div>
  </div>
  <div id="whatson" class="row">
    <div class="parallax3"></div>
  </div>
  <div class="row">
    <div class="infobox">
      <h2 class="mintitle">What's On?</h2>
      <% @taps.order(:abv).where(:now_on => true).each do |tap| %>
        <div class="beer texty"><%= tap.name %> | <%= tap.brewery %> | <%= tap.style %> | <%= tap.draft %> | <%= tap.abv %></div>
      <% end %>
    </div>
  <div id="events" class="row">
    <div class="parallax4"></div>
  </div>
  <div class="row">
    <div class="infobox">
      <h2 class="mintitle">Events</h2>
      <% @events.order(:scheduled_time).limit(5).each do |event| %>
        <div class="beer texty"><% if event.scheduled_time.wday == 0 %>
          Sunday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% elsif event.scheduled_time.wday == 1 %>
            Monday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% elsif event.scheduled_time.wday == 2 %>
            Tuesday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% elsif event.scheduled_time.wday == 3 %>
            Wednesday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% elsif event.scheduled_time.wday == 4 %>
            Thursday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% elsif event.scheduled_time.wday == 5 %>
            Friday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% elsif event.scheduled_time.wday == 6 %>
            Saturday, <%= localize(event.scheduled_time, :format => :long) %> | <%= event.name %> | <%= event.description %>
        <% end %></div>
      <% end %>
    </div>
  </div>
  <div id="contact" class="row">
    <div class="parallax5"></div>
  </div>
  <div class="row">
    <div class="infobox">
      <h2 class="mintitle">Contact Us</h2>
      <p class="texty">Contact us at +05555555555</p>
    </div>
  </div>
</div>

app/views/taps/_form.html.erb
<%= form_for(tap) do |f| %>
  <% if tap.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tap.errors.count, "error") %> prohibited this tap from being saved:</h2>

      <ul>
      <% tap.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :brewery %>
    <%= f.text_field :brewery %>
  </div>

  <div class="field">
    <%= f.label :style %>
    <%= f.text_field :style %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
  </div>

  <div class="field">
    <%= f.label :draft %>
    <%= f.text_field :draft %>
  </div>
  
  <div class="field">
    <%= f.label :abv %>
    <%= f.text_field :abv %>
  </div>
  
  <div class="field">
    <%= f.label :now_on %>
    <%= f.check_box :now_on %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taps/edit.html.erb
<h1 class="titlelogo">Editing Tap</h1>

<div class="row">
  <div class="buff col-xl-2 col-lg-2 col-md-2 col-sm-1 col-xs-1"></div>
  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-11 col-xs-1">
        <%= render 'form', tap: @tap %>

        <%= link_to 'Show', @tap %> |
        <%= link_to 'Back', taps_path %>
    </div>
</div>

app/views/taps/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="titlelogo">Taps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Brewery</th>
      <th>Style</th>
      <th>Color</th>
      <th>Description</th>
      <th>Img url</th>
      <th>Draft</th>
      <th>ABV</th>
      <th>Now On</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @taps.order(:brewery).each do |tap| %>
      <tr>
        <td><%= tap.name %></td>
        <td><%= tap.brewery %></td>
        <td><%= tap.style %></td>
        <td><%= tap.color %></td>
        <td><%= tap.description %></td>
        <td><%= tap.img_url %></td>
        <td><%= tap.draft %></td>
        <td><%= tap.abv %></td>
        <td><%= tap.now_on %></td>
        <td><%= link_to 'Show', tap %></td>
        <td><%= link_to 'Edit', edit_tap_path(tap) %></td>
        <td><%= link_to 'Destroy', tap, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tap', new_tap_path %>

app/views/taps/new.html.erb
<h1 class="titlelogo">New Tap</h1>

<div class="row">
  <div class="buff col-xl-2 col-lg-2 col-md-2 col-sm-1 col-xs-1"></div>
  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-11 col-xs-1">
        <%= render 'form', tap: @tap %>

        <%= link_to 'Back', taps_path %>
    </div>
</div>

app/views/taps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tap.name %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @tap.brewery %>
</p>

<p>
  <strong>Style:</strong>
  <%= @tap.style %>
</p>

<p>
  <strong>Color:</strong>
  <%= @tap.color %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tap.description %>
</p>

<p>
  <strong>Img url:</strong>
  <%= @tap.img_url %>
</p>

<p>
  <strong>Draft:</strong>
  <%= @tap.draft %>
</p>

<p>
  <strong>ABV:</strong>
  <%= @tap.abv %>
</p>

<p>
  <strong>Now On:</strong>
  <%= @tap.now_on %>
</p>

<%= link_to 'Edit', edit_tap_path(@tap) %> |
<%= link_to 'Back', taps_path %>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="titlelogo">Editing User</h1>

<div class="row">
    <div class="buff col-xl-2 col-lg-2 col-md-2 col-sm-1 col-xs-1"></div>
    <div class="col-xl-10 col-lg-10 col-md-10 col-sm-11 col-xs-1">
        <%= render 'form', user: @user %>

        <%= link_to 'Show', @user %> |
        <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="titlelogo">Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.order(:last_name).each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="titlelogo">New User</h1>

<div class="row">
    <div class="buff col-xl-2 col-lg-2 col-md-2 col-sm-1 col-xs-1"></div>
    <div class="col-xl-10 col-lg-10 col-md-10 col-sm-11 col-xs-1">
        <%= render 'form', user: @user %>

        <%= link_to 'Back', users_path %>
    </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="buff col-xl-2 col-lg-2 col-md-2 col-sm-1 col-xs-1"></div>
  <div class="col-xl-10 col-lg-10 col-md-10 col-sm-11 col-xs-1">
    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>
    
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user) %> |
    <%= link_to 'Back', users_path %>
  </div>
</div>